---
- name: 카프카 서버 중지
  systemd:
    state: stopped
    name: kafka-server
  ignore_errors: yes

- name: 카프카 디렉토리 삭제
  file:
    path: "{{ dir_path }}"
    state: absent
    when: init is defined

- name: 카프카 디렉토리 생성
  file:
    path: "{{ dir_path }}"
    state: directory
    mode: '0755'
    when: init is defined

- name: 카프카 다운
  get_url:
    url: https://archive.apache.org/dist/kafka/{{ kafkaversion }}/kafka_2.13-{{ kafkaversion }}.tgz
    dest: /opt/
    mode: '0600'
    when: init is defined

- name: 카프카 압축 해제
  unarchive:
    src: /opt/kafka_2.13-{{ kafkaversion }}.tgz
    dest: /usr/local
    remote_src: yes
    when: init is defined

- name: 카프카 심볼릭 링크
  file:
    path: /usr/local/kafka
    src: /usr/local/kafka_2.13-{{ kafkaversion }}
    state: link
    force: yes
    when: init is defined

- name: 카프카 심볼릭 링크 (홈)
  file:
    path: /home/{{  }}/kafka
    src: /usr/local/kafka_2.13-{{ kafkaversion }}
    state: link
    force: yes
    when: init is defined

- name: 카프카 서버 설정 복사
  template:
    src: server.properties.j2
    dest: /usr/local/kafka/config/server.properties
    mode: '0644'
    backup: no

- name: 카프카 기타 설정들 복사
  copy:
    src: "{{ item }}"
    dest: /usr/local/kafka/config/
    mode: '0644'
    backup: no
  with_items:
    - jmx

- name: 카프카의 kraft 스토리지 초기화. https://kafka.apache.org/documentation/#kraft_storage
  ansible.builtin.shell: sudo /usr/local/kafka/bin/kafka-storage.sh format -t eEtRVabwRWOFhWxJTI6uiA -c /usr/local/kafka/config/server.properties
  when: init is defined

- name: 카프카 서비스 systemd에 등록
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
    backup: no
  with_items:
    - kafka-server.service
  when: init is defined

- name: systemd의 설정파일들을 다시 불러와 변경된 설정 적용
  systemd:
    daemon_reload: yes

- name: 카프카 서버 시작
  systemd:
    state: started
    name: kafka-server
